name: SS.com Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"   # Основной запуск каждые 10 минут (страховка)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-telegram-bot==13.15

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python sscom_bot.py

      - name: Commit and push seen_ads.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_ads.json
          git commit -m "Update seen_ads.json" || echo "No changes to commit"
          git push

      - name: Sleep and trigger next run
        run: |
          echo "⏳ Ждём 10 минут перед повторным запуском..."
          sleep 600
          echo "🚀 Запускаем workflow снова!"
          gh workflow run "SS.com Telegram Bot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
