name: SS.com Notifier   # Название workflow, которое будет видно в GitHub Actions

on:
  schedule:
    - cron: "*/10 * * * *"  # Запуск каждые 10 минут
  workflow_dispatch:         # Возможность запускать вручную

jobs:
  run-bot:
    runs-on: ubuntu-latest    # GitHub будет использовать Linux-среду
    steps:
      - name: Скачать код из GitHub
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установить зависимости
        run: |
          pip install -r requirements.txt

      - name: Запустить бота
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python sscom_bot.py
