name: SS.com Notifier

on:
  workflow_dispatch:       # ручной запуск
  schedule:
    - cron: "*/10 * * * *" # каждые 10 минут (UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код из GitHub
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # важно для git push

      - name: Проверить права на git push
        run: |
          echo "🔍 Проверяем доступ к git remote..."
          git remote -v
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Пробуем сделать тестовый пуш в пустую ветку (без изменений)
          git commit --allow-empty -m "test-push" || echo "❌ Нет изменений для коммита"
          git push || echo "⚠️ Ошибка при git push — проверь настройки GITHUB_TOKEN"

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установить зависимости
        run: |
          pip install -r requirements.txt

      - name: Запустить бота
        run: python sscom_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Сохранить обновлённый seen_ads.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add seen_ads.json
          git commit -m "Update seen_ads.json" || echo "⚠️ Нет новых данных для сохранения"
          git push || echo "⚠️ Ошибка при git push"
