name: SS.com Notifier

on:
  workflow_dispatch:        # Запуск вручную
  schedule:
    - cron: "*/10 * * * *"  # Каждые 10 минут (UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код из GitHub
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # Нужно для git push

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установить зависимости
        run: |
          pip install requests beautifulsoup4

      - name: Запустить бота
        run: python sscom_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Проверить изменения seen_ads.json
        run: |
          if [ -n "$(git status --porcelain seen_ads.json)" ]; then
            echo "Файл seen_ads.json изменился, делаем commit..."
            git config --global user.email "bot@example.com"
            git config --global user.name "GitHub Actions Bot"
            git add seen_ads.json
            git commit -m "Update seen_ads.json [bot]"
            git push
          else
            echo "Файл seen_ads.json без изменений."
          fi
