name: SS.com Notifier

on:
  workflow_dispatch:       # запуск вручную
  schedule:
    - cron: "*/10 * * * *" # каждые 10 минут (по UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Скачать код из GitHub
        uses: actions/checkout@v3

      - name: 🗂 Кэшировать seen_ads.json
        uses: actions/cache@v3
        with:
          path: seen_ads.json
          key: seen-ads-cache

      - name: 🐍 Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Установить зависимости
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install requests beautifulsoup4

      - name: 🕒 Лог времени
        run: echo "Запуск по расписанию: $(date)"

      - name: 🚀 Запустить бота
        run: |
          echo "=== Старт бота ==="
          python sscom_bot.py
          echo "=== Конец работы ==="
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
