name: SS.com Notifier

on:
  schedule:
    - cron: "*/10 * * * *"   # каждые 10 минут
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Запустить бота
        run: python sscom_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit seen_ads.json
        run: |
          if [ -f seen_ads.json ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add seen_ads.json
            git commit -m "Update seen_ads.json [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "Файл seen_ads.json не найден!"
          fi
       - name: Commit updated seen_ads.json
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add seen_ads.json
    git commit -m "Update seen_ads.json" || echo "No changes to commit"
    git push   
