name: SS.com Notifier

on:
  workflow_dispatch:       # позволяет запускать вручную
  schedule:
    - cron: "*/10 * * * *" # запуск каждые 10 минут (по UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Скачать код из GitHub
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Установить зависимости
        run: |
          pip install -r requirements.txt

      - name: Лог времени
        run: echo "Запуск по расписанию: $(date)"

      - name: Запустить бота
        run: python sscom_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
